export default [
  {
    id: 1,
    title: "Naradan (2022)",
    rating: 7.3,
    img: "https://image.tmdb.org/t/p/w185/pZ4fVh4NG18D4mbf0lJGoAzfT0E.jpg",
    year: 2022,
    type: "Bollywood, Drama, Thriller",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 2,
    title: "Umma (2022)",
    rating: 5.1,
    img: "https://image.tmdb.org/t/p/w185/moLnqJmZ00i2opS0bzCVcaGC0iI.jpg",
    year: 2022,
    type: "Drama, Horror, Mystery",
    desc: "Amanda and her daughter live a quiet life on an American farm, but when the remains of her estranged mother arrive from Korea, Amanda becomes haunted by the fear of turning into her own mother.",
    director: "Iris Shim",
    length: "1h 24m",
    cast: "Sandra Oh as Amanda,Fivel Stewart as Chris,Dermot Mulroney as Danny",
  },
  {
    id: 3,
    title: "Etharkkum Thunindhavan (2022)",
    rating: 8.2,
    img: "https://image.tmdb.org/t/p/w185/5BU4qoPUPiOSiLue8ni8VdxNP4U.jpg",
    year: 2022,
    type: "Action, Bollywood, Drama, Thriller",
    desc: "When a lawyer uncovers a ruthless leader's criminal network that sexually exploits and threatens young women, he embarks on a bloody pursuit of justice.",
    director: " Pandiraj",
    length: "2h 31m",
    cast: "Suriya as Adv. Kannabiran a.k.a. Kanna,Priyanka Arul Mohan as Aadhini Kannabiran,Sathyaraj as Aadhirayar, Kannabiran's father",
  },
  {
    id: 4,
    title: "(18+)Island of Desire (2022)",
    rating: 7.8,
    img: "https://image.tmdb.org/t/p/w185/dPkbeU0ZT6tuO87TksSDLpnLXwR.jpg",
    year: 2022,
    type: "Adult, Asian, Drama, Thriller",
    desc: "Island of Desire (Philippines Movie); A nurse is assigned to work at an island called Isla Bato, where men treat women with lust.",
    director: " Kim Jin-sung",
    length: "1h 32m",
    cast: "Kim Hwa-yeon, Park Cho-hyeon, Han Jae Bum, Lee Min Shik, Yu Naang",
  },
  {
    id: 5,
    title: "The Outfit (2022)",
    rating: 7.5,
    img: "https://channelmyanmar.org/wp-content/uploads/2022/04/zbGN4QBrKoT3HO7etj4FvlM3OZb.jpg",
    year: 2022,
    type: " Crime, Drama",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 6,
    title: "Battle: Freestyle (2022)",
    rating: 4.8,
    img: "https://channelmyanmar.org/wp-content/uploads/2022/04/battle.freestyle.png",
    year: 2022,
    type: "Drama, Music, Romance",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 7,
    title: "Moonshot (2022)",
    rating: 5.5,
    img: "https://image.tmdb.org/t/p/w185/thqgzBPEDYQX0taszVus5nYMtTZ.jpg",
    year: 2022,
    type: " Comedy, Romance, Sci-Fi",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 8,
    title: "Pinocchio: A True Story (2022)",
    rating: 4.4,
    img: "https://image.tmdb.org/t/p/w185/9g6yLno4P14UWiURoL2H2NUp39h.jpg",
    year: 2022,
    type: " Animation, Family, Fantasy",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 9,
    title: "Sharmaji Namkeen (2022)",
    rating: 8.5,
    img: "https://image.tmdb.org/t/p/w185/hGsI606hmcpPkUpt9iHBMDpxlKk.jpg",
    year: 2022,
    type: "Bollywood, Comedy, Drama, Romance",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 10,
    title: "The Bubble (2022)",
    rating: "",
    img: "https://image.tmdb.org/t/p/w185/edYk5TSowZIDv138bCpF5ls3XI5.jpg",
    year: 2022,
    type: " Comedy",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 11,
    title: "Kothala Rayudu (2022)",
    rating: 8.9,
    img: "https://channelmyanmar.org/wp-content/uploads/2022/04/MV5BMjg5NGZmNjktODlhYy00MGY2LThhOWYtNGNkNDZkY2I1OGQxXkEyXkFqcGdeQXVyOTc2MTgwNjY@._V1_FMjpg_UX1000_.jpg",
    year: 2022,
    type: "Action, Romance",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 12,
    title: "Better Nate Than Ever (2022)",
    rating: 6.3,
    img: "https://image.tmdb.org/t/p/w185/55gkFbie2Nbudo21rDpi6zG0XvC.jpg",
    year: 2022,
    type: "Comedy, Family, Musical",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 13,
    title: "Cheaper by the Dozen (2022)",
    rating: 4.1,
    img: "https://image.tmdb.org/t/p/w185/qNRsouZh5zmhaE3n4QpLDXzy1gQ.jpg",
    year: 2022,
    type: "Adventure, Comedy, Family",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 14,
    title: "Hey! Sinamika (2022)",
    rating: 6.3,
    img: "https://image.tmdb.org/t/p/w185/8hHZrSDD5hOgSlB88yYELzQsr23.jpg",
    year: 2022,
    type: "Bollywood, Drama, Romance",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 15,
    title: "The Contractor (2022)",
    rating: 6,
    img: "https://image.tmdb.org/t/p/w185/rJPGPZ5soaG27MK90oKpioSiJE2.jpg",
    year: 2022,
    type: "Action, Thriller",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 16,
    title: "Radhe Shyam (2022)",
    rating: 6.9,
    img: "https://channelmyanmar.org/wp-content/uploads/2022/04/radhe.jpg",
    year: 2022,
    type: "Bollywood, Drama, Romance",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 17,
    title: "Adam by Eve: A Live in Animation...",
    rating: 6.5,
    img: "https://image.tmdb.org/t/p/w185/vI3aahilqPyMpNQQ7421GSEHRLX.jpg",
    year: 2022,
    type: "Animation, Music",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 18,
    title: "The Girl on the Mountain (2022)",
    rating: 4.9,
    img: "https://channelmyanmar.org/wp-content/uploads/2022/03/MV5BZDdmMjkyYzEtZDMwZi00NjczLTg0ZDktYjBkYjMxZjA3N2QwXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_-scaled.jpg",
    year: 2022,
    type: "Drama, Thriller",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 19,
    title: "Dragon Knight (2022)",
    rating: 5.8,
    img: "https://image.tmdb.org/t/p/w185/zkGFADykBtfPfTv7YJooxTH52ph.jpg",
    year: 2022,
    type: "Fantasy",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
  {
    id: 20,
    title: "After the Pandemic (2022)",
    rating: 5.0,
    img: "https://channelmyanmar.org/wp-content/uploads/2022/03/MV5BZTAyYWJkNDQtZjY4NS00ZTVlLTg1ODYtNjE5N2NlMzY3OGE1XkEyXkFqcGdeQXVyMjM1MDQxOQ@@._V1_-scaled.jpg",
    year: 2022,
    type: "Drama, Sci-Fi",
    desc: "Naradan is a dramatic journey of Chandraprakash, a popular news anchor in the media world who is desperate to prove his worth.",
    director: "Aashiq Abu",
    length: "2h 29m",
    cast: "Tovino Thomas as Chandraprakash,Anna Ben as Shaakira Mohammed,Sharafudheen as Pradeep John",
  },
];
